apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ingress-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
        - name: blue-app
          image: devopswithcloudhub/nginx:blue
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-ingress-blue
spec:
  type: NodePort
  selector:
    app: blue-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

