apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ingress-blue
spec:
  replicas: 1
  selector:
     matchLabels:
       app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
        - name: blue-app
          image: devopswithcloudhub/nginx:blue #blue-app
          ports:
            - containerPort: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: deploy-ingress-blue
spec:
  selector:
     app: blue-app
  type: ClusterIP
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
